### ISSUE TITLE
 Integrate invenio-administration

### ISSUE THREAD

**Issue by anikachurilova** [inveniosoftware/invenio-banners#10]
Add possibility to CRUD banners via the Administration web UI

Notes discussed on demo presentation:

Edit view

- [x] * change the Active widget to checkbox/slider
- [x] * change the Message input to be multiline 
- [x] * category field: make the helper text more clear, the categories match to colors/styles... not very clear for the user (they will not know what color to expect?)
- [x] * reorder the fields: message first, then category, then URL path, then start/end, then active (or suggestions) - moved to a task https://github.com/inveniosoftware/invenio-administration/issues/155

List view

- [x] * make the Message col much larger, it is the most important
- [x] * remove Created/Updated/Category/Message from sorting
- [x] * remove column Created
- [x] * fix the "loading" gif position

**Comment by ppanero** [comment]
missing invenio-banners PR

**Comment by ppanero** [comment]
The PR in invenio-banner has not been merged yet, let's not close the issue until then to avoid losing track @anikachurilova
